Dans un run os.system("python agent_gym.py --sell_to_grid") je crois puisque premier print "sell to the grid":


Traceback (most recent call last):
  File "agent_gym.py", line 94, in <module>
    model.learn(total_timesteps=len_episode*num_episode, callback=callback)
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/stable_baselines/deepq/dqn.py", line 219, in learn
    new_obs, rew, done, info = self.env.step(env_action)
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/stable_baselines/common/vec_env/base_vec_env.py", line 150, in step
    return self.step_wait()
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/stable_baselines/common/base_class.py", line 1110, in step_wait
    obs, rewards, dones, information = self.venv.step_wait()
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 44, in step_wait
    self.envs[env_idx].step(self.actions[env_idx])
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/stable_baselines/bench/monitor.py", line 91, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/vpere/Documents/Escape32/Reinforcement_learning/envs/microgrid_control_gymenv.py", line 161, in step
    self.save_plot_every()
  File "/home/vpere/Documents/Escape32/Reinforcement_learning/envs/microgrid_control_gymenv.py", line 205, in save_plot_every
    plot.save()
  File "/home/vpere/Documents/Escape32/Reinforcement_learning/render/testplot.py", line 60, in save
    df["Surplus"]=self.info["Energy Surplus"]
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3612, in __setitem__
    self._set_item(key, value)
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3784, in _set_item
    value = self._sanitize_column(value)
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 4509, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/vpere/Documents/Escape32/venv/lib/python3.7/site-packages/pandas/core/common.py", line 532, in require_length_match
    "Length of values "
ValueError: Length of values (9946) does not match length of index (8758)

Process finished with exit code 0

